apiVersion: v1
kind: Pod
metadata:
  name: frontend
  namespace: roboshop
  labels:
    project: roboshop
    environment: devolopment
    version: v1
    component: frontend
spec:   
  containers:
  - name: nginx
    image: nginx