apiVersion: v1
kind: Pod
metadata:
  name: annotations
  annotations:
    jenkins.url: "https://github.com/eksctl-io/eksctl/blob/main/examples/19-kms-cluster.yaml"
spec: 
  containers:
    name: nginx
    image: nginx