apiVersion: v1
kind: Pod
metadata:
  name: resources
spec: 
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        memory: "68mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"

